### ISSUE TITLE
Improvements over other lists

### ISSUE THREAD

**Issue by dougg0k** [FSPinho/react-native-speedy-list#1]
Hey,

What are the improvements of this library over the other options like FlatList and BigList?

**Comment by FSPinho** [comment]
Hi, @dougg0k 
This is definitely a missing section in the README! 🙂

For FlatList, the improvement was over the performance itself, since Speedy List uses a recycling method. For BigList, I had problems with large lists being constantly updated (elements being added, removed and changed), either in terms of performance, and to keep a consistent scrolling.

Thanks for your comment.

**Comment by dougg0k** [comment]
Sounds nice, I mean, if you guys are able to add all the helper props that those libs provide, it could turn into a really good library.

Thanks.
